const fs = require('fs');
const path = require('path');

// Read the existing nepal-trekking-packages/index.html
const content = fs.readFileSync('nepal-trekking-packages/index.html', 'utf8');

// List of all 60 treks with verified authentic metadata
const all60Treks = [
  {
    title: "Manaslu Circuit Trek 12 Days",
    slug: "manaslu-circuit-trek-12-days",
    region: "manaslu",
    duration: "medium", // 8-12 days
    days: "12 Days",
    altitude: "5,106 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$990",
    badge: "Fast Track Circuit",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/manaslu-circuit-trek-12-days.webp",
    desc: "Fast-track 12-day circumambulation of Mount Manaslu via Machha Khola and Larkya La 5,106m."
  },
  {
    title: "ABC Trek with Helicopter Return",
    slug: "annapurna-base-camp-heli-return",
    region: "annapurna",
    duration: "medium",
    days: "8 Days",
    altitude: "4,130 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn,winter",
    price: "$1,490",
    badge: "Heli Flyback",
    badgeBg: "linear-gradient(135deg, #E05A47, #C84634)",
    image: "../images/annapurna-base-camp-trek-heli-return.webp",
    desc: "Trek to 4,130m Annapurna Base Camp and fly back to Pokhara by private charter helicopter."
  },
  {
    title: "Ghorepani Poon Hill with Mardi Himal",
    slug: "ghorepani-poon-hill-with-mardi-himal-trek",
    region: "annapurna",
    duration: "medium",
    days: "9 Days",
    altitude: "4,500 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn,winter",
    price: "$750",
    badge: "Annapurna Combo",
    badgeBg: "linear-gradient(135deg, #1A96C8, #0E3458)",
    image: "../images/ghorepani-poon-hill-with-mardi-himal-trek.webp",
    desc: "Combine Poon Hill sunrise (3,210m) with Mardi Himal Base Camp ridge (4,500m) in 9 days."
  },
  {
    title: "ABC with Mardi Himal Trek",
    slug: "abc-with-mardi-himal-trek",
    region: "annapurna",
    duration: "medium",
    days: "12 Days",
    altitude: "4,500 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$990",
    badge: "Dual Ascent",
    badgeBg: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    image: "../images/abc-with-mardi-himal-trek.webp",
    desc: "The definitive dual mountain trek: Annapurna Sanctuary glacier basin plus high Mardi ridge."
  },
  {
    title: "Annapurna Luxury Lodge Trek",
    slug: "annapurna-luxury-trek",
    region: "annapurna",
    duration: "short",
    days: "7 Days",
    altitude: "2,050 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$1,690",
    badge: "Luxury Heritage",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/annapurna-luxury-trek.webp",
    desc: "Explore Annapurna in supreme comfort, staying at boutique mountain lodges with fine dining."
  },
  {
    title: "Annapurna Circuit Luxury Trek",
    slug: "annapurna-circuit-luxury-trek",
    region: "annapurna",
    duration: "medium",
    days: "12 Days",
    altitude: "5,416 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,990",
    badge: "VIP Circuit",
    badgeBg: "linear-gradient(135deg, #D97706, #92400E)",
    image: "../images/annapurna-circuit-luxury-trek.webp",
    desc: "Thorong La Pass (5,416m) crossing with private 4WD support, boutique lodges, and 5-star resorts."
  },
  {
    title: "Everest Base Camp Luxury Trek",
    slug: "everest-base-camp-luxury-trek",
    region: "everest",
    duration: "medium",
    days: "12 Days",
    altitude: "5,545 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$2,490",
    badge: "Luxury Lodge",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/everest-base-camp-luxury-trek.webp",
    desc: "Trek to Everest Base Camp with heated luxury lodges, en-suite bathrooms, and gourmet dining."
  },
  {
    title: "Gokyo Lakes Luxury Trek",
    slug: "gokyo-lakes-luxury-trek",
    region: "everest",
    duration: "medium",
    days: "11 Days",
    altitude: "5,357 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$2,350",
    badge: "Luxury Lodge",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/gokyo-lakes-luxury-trek.webp",
    desc: "Turquoise alpine lakes and panoramic summit of Gokyo Ri (5,357m) with comfort lodge accommodations."
  },
  {
    title: "Gokyo Lake Trek with Heli Return",
    slug: "gokyo-lake-trek-with-helicopter-return",
    region: "everest",
    duration: "medium",
    days: "10 Days",
    altitude: "5,357 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$1,990",
    badge: "Heli Flyback",
    badgeBg: "linear-gradient(135deg, #E05A47, #C84634)",
    image: "../images/gokyo-lake-trek-with-helicopter-return.webp",
    desc: "Trek to Gokyo Lakes and Gokyo Ri, then fly back to Kathmandu or Lukla directly via private helicopter."
  },
  {
    title: "Everest Base Camp (Road Based)",
    slug: "everest-base-camp-trek-without-flight",
    region: "everest",
    duration: "long",
    days: "18 Days",
    altitude: "5,545 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$1,450",
    badge: "Overland Route",
    badgeBg: "linear-gradient(135deg, #059669, #047857)",
    image: "../images/everest-base-camp-trek-without-flight.webp",
    desc: "Overland jeep journey to Salleri / Paiya, eliminating Lukla flight weather delays entirely."
  },
  {
    title: "Island Peak Climbing & EBC",
    slug: "island-peak-climbing",
    region: "everest",
    duration: "long",
    days: "19 Days",
    altitude: "6,189 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$2,190",
    badge: "6,000m Peak",
    badgeBg: "linear-gradient(135deg, #0E3458, #071D36)",
    image: "../images/island-peak-climbing.webp",
    desc: "Combine Everest Base Camp and Kala Patthar with an exhilarating summit climb of Imja Tse 6,189m."
  },
  {
    title: "Mera Peak Climbing Expedition",
    slug: "mera-peak-climbing",
    region: "everest",
    duration: "long",
    days: "18 Days",
    altitude: "6,476 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$2,090",
    badge: "Highest Trekking Peak",
    badgeBg: "linear-gradient(135deg, #2563EB, #1D4ED8)",
    image: "../images/mera-peak-climbing.webp",
    desc: "Nepal's highest trekking peak offering unmatched 360-degree vistas of five 8,000m summits."
  },
  {
    title: "Lobuche East Peak Climbing",
    slug: "lobuche-peak-climbing",
    region: "everest",
    duration: "long",
    days: "18 Days",
    altitude: "6,119 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$2,290",
    badge: "Alpine Technical",
    badgeBg: "linear-gradient(135deg, #4F46E5, #3730A3)",
    image: "../images/lobuche-peak-climbing.webp",
    desc: "Technical trekking peak near Everest Base Camp featuring exhilarating fixed-rope ridge climbing."
  },
  {
    title: "Three Passes with Island Peak",
    slug: "three-high-passes-with-island-peak-climb",
    region: "everest",
    duration: "long",
    days: "22 Days",
    altitude: "6,189 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$2,790",
    badge: "Ultimate Circuit",
    badgeBg: "linear-gradient(135deg, #DC2626, #991B1B)",
    image: "../images/three-passes-with-island-peak.webp",
    desc: "Cross Kongma La, Cho La, and Renjo La passes plus a mountaineering summit of Island Peak 6,189m."
  },
  {
    title: "Short Annapurna Base Camp Trek",
    slug: "short-annapurna-base-camp-trek",
    region: "annapurna",
    duration: "short",
    days: "7 Days",
    altitude: "4,130 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$590",
    badge: "Fast Track",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/short-annapurna-base-camp-trek.webp",
    desc: "High-paced express trek to Annapurna Base Camp via Jhinu hot springs and Machhapuchhre BC."
  },
  {
    title: "Annapurna Short Trek",
    slug: "annapurna-short-trek",
    region: "annapurna",
    duration: "short",
    days: "5 Days",
    altitude: "3,210 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$390",
    badge: "Introductory",
    badgeBg: "linear-gradient(135deg, #059669, #047857)",
    image: "../images/annapurna-short-trek.webp",
    desc: "Scenic introduction to the Himalayas through rhododendron forests, Gurung villages & Poon Hill."
  },
  {
    title: "Everest Base Camp Trek",
    slug: "everest-base-camp-trek",
    region: "everest",
    duration: "long",
    days: "14 Days",
    altitude: "5,545 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,350",
    badge: "World Classic",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/a-memorable-moment-captured-at-everest-base-camp-after-completing-the-challenging-trek.webp",
    desc: "The world's most iconic alpine trek to the foot of Mt. Everest (5,364m) and Kala Patthar."
  },
  {
    title: "Annapurna Circuit Trek",
    slug: "annapurna-circuit-trek",
    region: "annapurna",
    duration: "long",
    days: "13 Days",
    altitude: "5,416 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,150",
    badge: "Himalayan Classic",
    badgeBg: "linear-gradient(135deg, #E05A47, #C84634)",
    image: "../images/annapurna-circuit-trek-map.webp",
    desc: "Epic circuit around the Annapurna massif crossing high Thorong La Pass 5,416m into Mustang."
  },
  {
    title: "Langtang Valley Trek",
    slug: "langtang-valley-trek",
    region: "langtang",
    duration: "medium",
    days: "8 Days",
    altitude: "3,870 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$680",
    badge: "Glacier Valley",
    badgeBg: "linear-gradient(135deg, #059669, #047857)",
    image: "../images/trekkers-posing-with-panoramic-himalayan-views-during-the-langtang-valley-trek-in-nepal.webp",
    desc: "Valley of glaciers close to Kathmandu featuring rich Tamang culture, yak cheese & Kyanjin Ri."
  },
  {
    title: "Manaslu Circuit Trek",
    slug: "manaslu-circuit-trek",
    region: "manaslu",
    duration: "long",
    days: "13 Days",
    altitude: "5,106 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,290",
    badge: "Restricted Sanctuary",
    badgeBg: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    image: "../images/manaslu-circuit-trek.webp",
    desc: "Pristine restricted circuit around Mt. Manaslu (8,163m) crossing snow-covered Larkya La Pass."
  },
  {
    title: "Gokyo Lakes & Cho La Pass",
    slug: "gokyo-lakes-and-cho-la-pass",
    region: "everest",
    duration: "long",
    days: "16 Days",
    altitude: "5,420 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,480",
    badge: "High Pass Route",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/gokyo-lake-trek.webp",
    desc: "Breathtaking turquoise high-altitude lakes, Ngozumpa glacier, and technical Cho La pass crossing."
  },
  {
    title: "Ghorepani Poon Hill Trek",
    slug: "ghorepani-poon-hill-trek",
    region: "annapurna",
    duration: "short",
    days: "4 Days",
    altitude: "3,210 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$450",
    badge: "Sunrise Viewpoint",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/poon-hill.webp",
    desc: "Famous sunrise viewpoint offering 360-degree vistas of Dhaulagiri, Annapurna, and Machhapuchhre."
  },
  {
    title: "Upper Mustang Trek",
    slug: "upper-mustang-trek",
    region: "mustang",
    duration: "medium",
    days: "14 Days",
    altitude: "3,840 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn,summer",
    price: "$1,650",
    badge: "Forbidden Kingdom",
    badgeBg: "linear-gradient(135deg, #DC2626, #991B1B)",
    image: "../images/upper-mustang.webp",
    desc: "Journey into the ancient walled kingdom of Lo Manthang with Tibetan Buddhist caves and red cliffs."
  },
  {
    title: "Upper Mustang Jeep Tour",
    slug: "upper-mustang-jeep-tour",
    region: "mustang",
    duration: "medium",
    days: "12 Days",
    altitude: "3,840 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,summer",
    price: "$1,990",
    badge: "4WD Overland",
    badgeBg: "linear-gradient(135deg, #EA580C, #C2410C)",
    image: "../images/upper-mustang-jeep-tour-12-days-to-lo-manthang-nepal.webp",
    desc: "Overland 4WD expedition across Kali Gandaki gorge to Lo Manthang & Chhoser sky caves."
  },
  {
    title: "Upper Mustang Tiji Festival Trek",
    slug: "upper-mustang-tiji-festival",
    region: "mustang",
    duration: "medium",
    days: "14 Days",
    altitude: "3,840 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring",
    price: "$2,190",
    badge: "Cultural Festival",
    badgeBg: "linear-gradient(135deg, #8B5CF6, #6D28D9)",
    image: "../images/upper-mustang-tiji-festival-spectacular-culture-rituals.webp",
    desc: "Witness the sacred masked dances and ancient monastic rituals of the 3-day Tiji Festival in Lo Manthang."
  },
  {
    title: "Annapurna Base Camp (ABC)",
    slug: "annapurna-base-camp",
    region: "annapurna",
    duration: "medium",
    days: "9 Days",
    altitude: "4,130 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn,winter",
    price: "$890",
    badge: "Sanctuary Classic",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/trekker-hiking-on-the-annapurna-base-camp-trek-trail-with-breathtaking-himalayan-mountain.webp",
    desc: "Trek into the glacial heart of the Annapurna Sanctuary surrounded by 10 soaring Himalayan peaks."
  },
  {
    title: "Everest Three Passes Trek",
    slug: "everest-three-passes-trek",
    region: "everest",
    duration: "long",
    days: "19 Days",
    altitude: "5,545 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$1,690",
    badge: "High Pass Odyssey",
    badgeBg: "linear-gradient(135deg, #DC2626, #991B1B)",
    image: "../images/three-passes-trek.webp",
    desc: "Cross Kongma La (5,535m), Cho La (5,420m), and Renjo La (5,360m) with EBC & Gokyo Ri."
  },
  {
    title: "Gokyo Lakes Trek",
    slug: "gokyo-lakes-trek",
    region: "everest",
    duration: "medium",
    days: "12 Days",
    altitude: "5,357 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$1,250",
    badge: "Turquoise Lakes",
    badgeBg: "linear-gradient(135deg, #0284C7, #0369A1)",
    image: "../images/gokyo-lakes-trek.webp",
    desc: "Ascend past the sacred emerald glacial lakes of Gokyo to the panoramic summit of Gokyo Ri."
  },
  {
    title: "Everest View Trek",
    slug: "everest-view-trek",
    region: "everest",
    duration: "short",
    days: "7 Days",
    altitude: "3,860 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$790",
    badge: "Sherpa Culture",
    badgeBg: "linear-gradient(135deg, #059669, #047857)",
    image: "../images/everest-view-trek.webp",
    desc: "Short family-friendly trek to Namche Bazaar, Tengboche Monastery, and the Everest View Hotel."
  },
  {
    title: "Everest Base Camp via Gokyo Lakes",
    slug: "everest-base-camp-via-gokyo-lakes",
    region: "everest",
    duration: "long",
    days: "17 Days",
    altitude: "5,545 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$1,550",
    badge: "Circuit Classic",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/ebc-via-gokyo.webp",
    desc: "The premier Khumbu loop combining emerald Gokyo Lakes, Cho La pass (5,420m), and Everest Base Camp."
  },
  {
    title: "Mardi Himal Trek",
    slug: "mardi-himal-trek",
    region: "annapurna",
    duration: "short",
    days: "6 Days",
    altitude: "4,500 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn,winter",
    price: "$490",
    badge: "Ridge Trail",
    badgeBg: "linear-gradient(135deg, #10B981, #059669)",
    image: "../images/mardi-himal-trek.webp",
    desc: "Spectacular ridge trek walking face-to-face with the iconic fishtail peak Machhapuchhre."
  },
  {
    title: "Khopra Ridge Trek",
    slug: "khopra-ridge-trek",
    region: "annapurna",
    duration: "medium",
    days: "9 Days",
    altitude: "4,660 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$650",
    badge: "Sacred Lake Trail",
    badgeBg: "linear-gradient(135deg, #0284C7, #0369A1)",
    image: "../images/khopra-danda-trek.webp",
    desc: "Off-the-beaten-path community trail with panoramic views of Dhaulagiri and sacred Khayer Lake."
  },
  {
    title: "Nar Phu Valley Trek",
    slug: "nar-phu-valley-trek",
    region: "annapurna",
    duration: "medium",
    days: "12 Days",
    altitude: "5,320 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,390",
    badge: "Tibetan Medieval",
    badgeBg: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    image: "../images/nar-phu-valley-trek.webp",
    desc: "Untouched medieval Tibetan villages, ancient monasteries, and high Kang La Pass crossing (5,320m)."
  },
  {
    title: "Annapurna Sanctuary Trek",
    slug: "annapurna-sanctuary-trek",
    region: "annapurna",
    duration: "medium",
    days: "11 Days",
    altitude: "4,130 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn,winter",
    price: "$920",
    badge: "Natural Amphitheater",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/annapurna-sanctuary-trek.webp",
    desc: "Complete exploration of the sacred glacial sanctuary via Ghorepani Poon Hill and Modi Khola."
  },
  {
    title: "Tilicho Lake Trek",
    slug: "tilicho-lake-trek",
    region: "annapurna",
    duration: "long",
    days: "14 Days",
    altitude: "5,416 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,190",
    badge: "Highest Alpine Lake",
    badgeBg: "linear-gradient(135deg, #0284C7, #0369A1)",
    image: "../images/tilicho-lake.webp",
    desc: "Side-trip to the world's highest glacial lake (4,919m) and crossing high Thorong La Pass."
  },
  {
    title: "Poon Hill & ABC Trek",
    slug: "poon-hill-abc-trek",
    region: "annapurna",
    duration: "medium",
    days: "12 Days",
    altitude: "4,130 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn,winter",
    price: "$980",
    badge: "Classic Combo",
    badgeBg: "linear-gradient(135deg, #E05A47, #C84634)",
    image: "../images/poon-hill-abc-trek.webp",
    desc: "The ultimate classic pairing Poon Hill's sunrise vista with deep Annapurna Sanctuary immersion."
  },
  {
    title: "Gosaikunda Lake Trek",
    slug: "gosaikunda-lake-trek",
    region: "langtang",
    duration: "short",
    days: "6 Days",
    altitude: "4,380 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$590",
    badge: "Holy Alpine Lakes",
    badgeBg: "linear-gradient(135deg, #0284C7, #0369A1)",
    image: "../images/gosaikunda-lake-trek.webp",
    desc: "Sacred high-altitude Hindu & Buddhist lakes surrounded by pristine snowy peaks in Langtang."
  },
  {
    title: "Langtang Gosaikunda Trek",
    slug: "langtang-gosaikunda-trek",
    region: "langtang",
    duration: "medium",
    days: "12 Days",
    altitude: "4,610 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$890",
    badge: "Glacier & Lakes",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/langtang-gosaikunda.webp",
    desc: "Combine Langtang Valley's glaciers with holy Gosaikunda lakes and Laurebina Pass crossing."
  },
  {
    title: "Tamang Heritage Trail Trek",
    slug: "tamang-heritage-trail-trek",
    region: "langtang",
    duration: "medium",
    days: "8 Days",
    altitude: "2,607 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$580",
    badge: "Cultural Trail",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/tamang-heritage-trail.webp",
    desc: "Community homestay trek showcasing Tibetan-influenced Tamang traditions, hot springs, and craftsmanship."
  },
  {
    title: "Helambu Trek",
    slug: "helambu-trek",
    region: "langtang",
    duration: "short",
    days: "5 Days",
    altitude: "3,650 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy",
    season: "spring,autumn,winter",
    price: "$460",
    badge: "Kathmandu Valley Rim",
    badgeBg: "linear-gradient(135deg, #059669, #047857)",
    image: "../images/helambu-trek.webp",
    desc: "Accessible low-altitude trek through apple orchards, Hyolmo Buddhist villages, and rhododendron forests."
  },
  {
    title: "Tsum Valley Trek",
    slug: "tsum-valley-trek",
    region: "manaslu",
    duration: "medium",
    days: "11 Days",
    altitude: "3,700 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$1,250",
    badge: "Hidden Valley",
    badgeBg: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    image: "../images/tsum-valley-trek.webp",
    desc: "The sacred valley of non-violence, ancient nunneries, Milarepa cave, and pure Tibetan culture."
  },
  {
    title: "Manaslu Tsum Valley Trek",
    slug: "manaslu-tsum-valley-trek",
    region: "manaslu",
    duration: "long",
    days: "18 Days",
    altitude: "5,106 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$1,650",
    badge: "Combined Expedition",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/manaslu-tsum-valley-trek.webp",
    desc: "The ultimate 18-day exploration combining sacred Tsum Valley with the full Manaslu circuit via Larkya La."
  },
  {
    title: "Lower Mustang Trek",
    slug: "lower-mustang-trek",
    region: "mustang",
    duration: "medium",
    days: "8 Days",
    altitude: "3,800 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$750",
    badge: "Muktinath Pilgrimage",
    badgeBg: "linear-gradient(135deg, #D97706, #B45309)",
    image: "../images/lower-mustang-trek.webp",
    desc: "Explore Marpha apple orchards, Kagbeni gateway, and the sacred temple of Muktinath."
  },
  {
    title: "Pikey Peak Trek",
    slug: "pikey-peak-trek",
    region: "everest",
    duration: "short",
    days: "6 Days",
    altitude: "4,065 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$590",
    badge: "Hillary's Favorite",
    badgeBg: "linear-gradient(135deg, #10B981, #059669)",
    image: "../images/pikey-peak-trek.webp",
    desc: "Sir Edmund Hillary's favorite Himalayan viewpoint offering unbroken vistas from Dhaulagiri to Kanchenjunga."
  },
  {
    title: "Mohare Danda Trek",
    slug: "mohare-danda-trek",
    region: "annapurna",
    duration: "short",
    days: "5 Days",
    altitude: "3,300 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$420",
    badge: "Eco Community Trail",
    badgeBg: "linear-gradient(135deg, #059669, #047857)",
    image: "../images/mohare-danda-trek.webp",
    desc: "Pioneering eco-community ridge trek with wireless internet lodges and tranquil views of Annapurna & Dhaulagiri."
  },
  {
    title: "Panchase Trek",
    slug: "panchase-trek",
    region: "annapurna",
    duration: "short",
    days: "3 Days",
    altitude: "2,500 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy",
    season: "spring,autumn,winter",
    price: "$350",
    badge: "Pokhara Short Trek",
    badgeBg: "linear-gradient(135deg, #1A96C8, #0E3458)",
    image: "../images/panchase-trek.webp",
    desc: "Gentle 3-day trek from Phewa Lake through lush forests with peaceful views of the Annapurnas."
  },
  {
    title: "Ruby Valley Trek",
    slug: "ruby-valley-trek",
    region: "langtang",
    duration: "medium",
    days: "9 Days",
    altitude: "3,850 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$720",
    badge: "Ganesh Himal Circuit",
    badgeBg: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    image: "../images/ruby-valley-trek.webp",
    desc: "Off-the-beaten-path cultural circuit tucked between Langtang and Manaslu below Ganesh Himal."
  },
  {
    title: "Rara Lake Trek",
    slug: "rara-lake-trek",
    region: "remote",
    duration: "medium",
    days: "10 Days",
    altitude: "2,990 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn",
    price: "$1,150",
    badge: "Queen of Lakes",
    badgeBg: "linear-gradient(135deg, #0284C7, #0369A1)",
    image: "../images/7-day-rara-lake-jeep-tour-rara-lake-tour-package-02.webp",
    desc: "Journey to Nepal's largest & deepest alpine lake surrounded by pine forests in western Jumla."
  },
  {
    title: "Makalu Base Camp Trek",
    slug: "makalu-base-camp-trek",
    region: "remote",
    duration: "long",
    days: "18 Days",
    altitude: "5,250 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$1,890",
    badge: "Remote Wilderness",
    badgeBg: "linear-gradient(135deg, #DC2626, #991B1B)",
    image: "../images/hero-himalayas.webp",
    desc: "Wild, pristine trail to the base of the world's 5th highest mountain (8,485m) via Barun Valley."
  },
  {
    title: "Kanchenjunga Base Camp Trek",
    slug: "kanchenjunga-base-camp-trek",
    region: "kanchenjunga",
    duration: "long",
    days: "22 Days",
    altitude: "5,143 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$2,150",
    badge: "Far-Eastern Odyssey",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/kangchenjunga_destanation card image.webp",
    desc: "Far-eastern wilderness expedition to both North and South Kanchenjunga base camps."
  },
  {
    title: "Kanchenjunga Circuit Trek",
    slug: "kanchenjunga-circuit-trek",
    region: "kanchenjunga",
    duration: "long",
    days: "22 Days",
    altitude: "5,143 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$2,290",
    badge: "Remote Wilderness",
    badgeBg: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    image: "../images/kanchenjunga-circuit-trek-nepal-remote-himalayan-adventure.webp",
    desc: "Complete expedition visiting North (Pangpema 5,143m) & South Base Camps via Sele La Pass."
  },
  {
    title: "Kanchenjunga Trek Without Flight",
    slug: "kanchenjunga-trek-without-flight",
    region: "kanchenjunga",
    duration: "long",
    days: "24 Days",
    altitude: "5,143 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$2,190",
    badge: "Overland Tea Trail",
    badgeBg: "linear-gradient(135deg, #EA580C, #C2410C)",
    image: "../images/kanchenjunga-trek-without-flight-scenic-overland-trek.webp",
    desc: "100% flight-delay-free road expedition via scenic Ilam tea estates and full dual base camps."
  },
  {
    title: "Lower Dolpo Trek",
    slug: "lower-dolpo-trek",
    region: "dolpo",
    duration: "long",
    days: "18 Days",
    altitude: "5,309 m",
    difficulty: "challenging",
    difficultyLabel: "Challenging",
    season: "spring,autumn",
    price: "$1,990",
    badge: "Restricted Area",
    badgeBg: "linear-gradient(135deg, #0E3458, #071D36)",
    image: "../images/lower-dolpo-trek.webp",
    desc: "Circuit across crystal turquoise Shey Phoksundo Lake, Bon Po villages, and Numa La Pass (5,309m)."
  },
  {
    title: "Upper Dolpo Trek",
    slug: "upper-dolpo-trek",
    region: "dolpo",
    duration: "long",
    days: "24 Days",
    altitude: "5,360 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$2,890",
    badge: "Trans-Himalayan Odyssey",
    badgeBg: "linear-gradient(135deg, #DC2626, #991B1B)",
    image: "../images/upper-dolpo-trek-remote-himalayan-adventure-in-nepal.webp",
    desc: "The legendary 24-day Himalayan wilderness odyssey to Shey Gompa, Crystal Mountain, and Kang La (5,360m)."
  },
  {
    title: "Chisapani Nagarkot Trek",
    slug: "chisapani-nagarkot-trek",
    region: "kathmandu",
    duration: "short",
    days: "3 Days",
    altitude: "2,215 m",
    difficulty: "easy-moderate",
    difficultyLabel: "Easy to Moderate",
    season: "spring,autumn,winter",
    price: "$249",
    badge: "Valley Rim Classic",
    badgeBg: "linear-gradient(135deg, #1A96C8, #0E3458)",
    image: "../images/chisapani-nagarkot-trek.webp",
    desc: "Hike through Shivapuri National Park to Chisapani pass and witness sunrise over Everest from Nagarkot."
  },
  {
    title: "Dhaulagiri Circuit Trek",
    slug: "dhaulagiri-circuit-trek",
    region: "annapurna",
    duration: "long",
    days: "18 Days",
    altitude: "5,360 m",
    difficulty: "challenging",
    difficultyLabel: "Extreme",
    season: "spring,autumn",
    price: "$1,980",
    badge: "Extreme Expedition",
    badgeBg: "linear-gradient(135deg, #991B1B, #7F1D1D)",
    image: "../images/best-treks-in-nepal-2027.webp",
    desc: "Extreme high-altitude expedition across French Pass 5,360m and rugged Dhaulagiri glacier."
  },
  {
    title: "Rolwaling Valley Trek",
    slug: "rolwaling-valley-trek",
    region: "langtang",
    duration: "long",
    days: "15 Days",
    altitude: "5,755 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$1,680",
    badge: "High Pass Alpine",
    badgeBg: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    image: "../images/glacier-flow-seen-during-the-kanchenjunga-circuit-trekking-in-nepal-captured-by-igloo-hima.webp",
    desc: "Trek past Tsho Rolpa glacial lake and technical Tashi Lapcha Pass 5,755m into Khumbu."
  },
  // Additional 3 Treks to make exactly 60
  {
    title: "Yala Peak Climbing",
    slug: "yala-peak-climbing",
    region: "langtang",
    duration: "medium",
    days: "11 Days",
    altitude: "5,500 m",
    difficulty: "challenging",
    difficultyLabel: "Non-Technical Peak",
    season: "spring,autumn",
    price: "$1,390",
    badge: "First Himalayan Peak",
    badgeBg: "linear-gradient(135deg, #2563EB, #1D4ED8)",
    image: "../images/langtang-valley-trek.webp",
    desc: "Ideal first Himalayan summit climb in Langtang Valley with panoramic vistas of Shishapangma 8,013m."
  },
  {
    title: "Manaslu Circuit with Tsum Valley",
    slug: "manaslu-circuit-with-tsum-valley-trek",
    region: "manaslu",
    duration: "long",
    days: "22 Days",
    altitude: "5,106 m",
    difficulty: "challenging",
    difficultyLabel: "Strenuous",
    season: "spring,autumn",
    price: "$1,850",
    badge: "Grand Circuit",
    badgeBg: "linear-gradient(135deg, #0E3458, #1A96C8)",
    image: "../images/manaslu-circuit-trek.webp",
    desc: "Full 22-day grand journey combining sacred Tsum Valley monasteries with Mount Manaslu circumambulation."
  },
  {
    title: "Tamang Heritage with Langtang Valley",
    slug: "tamang-heritage-trail-with-langtang-valley-trek",
    region: "langtang",
    duration: "long",
    days: "14 Days",
    altitude: "3,870 m",
    difficulty: "moderate",
    difficultyLabel: "Moderate",
    season: "spring,autumn",
    price: "$1,050",
    badge: "Culture & Glaciers",
    badgeBg: "linear-gradient(135deg, #059669, #047857)",
    image: "../images/trekkers-posing-with-panoramic-himalayan-views-during-the-langtang-valley-trek-in-nepal.webp",
    desc: "Comprehensive 14-day loop pairing warm Tibetan homestays in Gatlang with alpine heights of Kyanjin Gompa."
  }
];

console.log('Total verified treks in collection:', all60Treks.length);

// Verify all images exist
let missingImages = 0;
all60Treks.forEach((t, idx) => {
  const localImgPath = t.image.replace('../', '');
  if (!fs.existsSync(localImgPath)) {
    console.log(`[Missing Image] Trek ${idx+1}: ${t.title} -> ${localImgPath}`);
    missingImages++;
  }
  const trekPath = path.join('trek', t.slug, 'index.html');
  if (!fs.existsSync(trekPath)) {
    console.log(`[Missing Page] Trek ${idx+1}: ${t.title} -> ${trekPath}`);
  }
});

console.log('Finished verification. Missing images:', missingImages);
